#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Apr 28 01:09:36 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_background = wx.Panel(self, -1)
        self.sizer_cover_staticbox = wx.StaticBox(self.panel_background, -1, "Cover image:")
        self.sizer_mp3s_staticbox = wx.StaticBox(self.panel_background, -1, "MP3s to tag:")
        self.main_frame_statusbar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)
        self.textctrl_curpath = wx.TextCtrl(self.panel_background, -1, "", style=wx.TE_READONLY)
        self.button_add_files = wx.Button(self.panel_background, -1, "Add &files...")
        self.button_add_dir = wx.Button(self.panel_background, -1, "Add &directory...")
        self.list_files = wx.ListBox(self.panel_background, -1, choices=[])
        self.button_open_image = wx.Button(self.panel_background, -1, "Open &image...")
        self.bitmap_art = wx.StaticBitmap(self.panel_background, -1, wx.NullBitmap, style=wx.SUNKEN_BORDER)
        self.button_write_tags = wx.Button(self.panel_background, -1, "&Write tags")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Add cover art")
        self.main_frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        main_frame_statusbar_fields = ["Add mp3s, choose a cover image and click 'Write tags'"]
        for i in range(len(main_frame_statusbar_fields)):
            self.main_frame_statusbar.SetStatusText(main_frame_statusbar_fields[i], i)
        self.list_files.SetMinSize((384, -1))
        self.bitmap_art.SetMinSize((256, 256))
        self.button_write_tags.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_wrapper = wx.BoxSizer(wx.VERTICAL)
        sizer_vertical1 = wx.BoxSizer(wx.VERTICAL)
        sizer_buttonbar = wx.BoxSizer(wx.HORIZONTAL)
        sizer_horizontal1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_cover = wx.StaticBoxSizer(self.sizer_cover_staticbox, wx.VERTICAL)
        sizer_mp3s = wx.StaticBoxSizer(self.sizer_mp3s_staticbox, wx.VERTICAL)
        sizer_add_files = wx.BoxSizer(wx.HORIZONTAL)
        sizer_add_files.Add(self.textctrl_curpath, 1, wx.EXPAND, 0)
        sizer_add_files.Add(self.button_add_files, 0, wx.LEFT, 6)
        sizer_add_files.Add(self.button_add_dir, 0, wx.LEFT, 6)
        sizer_mp3s.Add(sizer_add_files, 0, wx.ALL|wx.EXPAND, 6)
        sizer_mp3s.Add(self.list_files, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 6)
        sizer_horizontal1.Add(sizer_mp3s, 1, wx.ALL|wx.EXPAND, 6)
        sizer_cover.Add(self.button_open_image, 0, wx.ALL|wx.EXPAND, 6)
        sizer_cover.Add(self.bitmap_art, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 6)
        sizer_horizontal1.Add(sizer_cover, 0, wx.RIGHT|wx.TOP|wx.BOTTOM, 6)
        sizer_vertical1.Add(sizer_horizontal1, 1, wx.EXPAND, 0)
        sizer_buttonbar.Add((0, 0), 1, wx.EXPAND, 0)
        sizer_buttonbar.Add(self.button_write_tags, 0, wx.RIGHT|wx.TOP|wx.BOTTOM, 6)
        sizer_vertical1.Add(sizer_buttonbar, 0, wx.EXPAND, 0)
        self.panel_background.SetSizer(sizer_vertical1)
        sizer_wrapper.Add(self.panel_background, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_wrapper)
        sizer_wrapper.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class MainFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    main_frame = MainFrame(None, -1, "")
    app.SetTopWindow(main_frame)
    main_frame.Show()
    app.MainLoop()
